include:
  - board: eyelash_nano
    shield: offsetkey_peripheral_left
  - board: eyelash_nano
    shield: offsetkey_peripheral_right
  - board: nice_nano_v2
    shield: offsetkey_central_dongle dongle_display
    artifact-name: offsetkey_dongle
  - board: eyelash_nano
    shield: settings_reset
